### ISSUE TITLE
JS Issues

### ISSUE THREAD

**Issue by OmgImAlexis** [SickRage/old-sickrage-issues#146]
Since I'll be gone for most of the week please comment all issues I need to see in here as I'm not going to be viewing any notifications till at least Saturday.

@SickRage/collaborators @SickRage/moderators

**Comment by OmgImAlexis** [comment]
@alisonatwork @Thraxis I'll update the docs for how to run the grunt tasks when I'm free.

Basically to "build" the min files for SASS, CSS and Javascript just run `cd .build && npm install && grunt`.

**Comment by miigotu** [comment]
and no more need for -g either =P

**Comment by Amadeus-** [comment]
I'm not sure if the docs include instructions on installing npm/nvm, but that would be good to have.

Also, as far as I can tell, nvm *requires* a bash shell to run.   So, it might be good to mention that in the docs and include this suggestion if people have other shells they prefer to use (e.g., 'tcsh', like me.)   Basically, I created a build.sh file in my SickRage root directory and put this in it:
```
#!/bin/bash
source ~/.profile
cd .build
npm install
grunt
```
(Obviously, this method requires that nvm is installed with the default options, etc.)

**Comment by OmgImAlexis** [comment]
@Amadeus- I might look into adding a script to setup nvm, node, npm, etc. on *NIX and Windows just so it's another step people don't need to worry about.

**Comment by Rycochet** [comment]
Just pointing out if you do instructions / script then I've found that OSX requires ```sudo npm install``` to work - even for non-globals - makes it hard to deploy code to colleagues on those machines...

**Comment by OmgImAlexis** [comment]
OSX doesn't need `sudo` at all if you've got it installed correctly. I'm assuming you're on El Capitan?
I know this as I'm running OSX myself and even on El Capitan with the new rootless mode I still don't need `sudo`.

Try using [nvm](https://github.com/creationix/nvm) instead of brew or whatever other way you installed it.

**Comment by alisonatwork** [comment]
@Rycochet - there is a common problem with sudo and Node/npm on MacOS, and i don't think it has to do with this project per se. Although running it with sudo may seem to work at first, it will then install a bunch of stuff as root in your home directory which leads to bigger problems down the track and you end up having to sudo for everything. I can't remember exactly how to fix it since I don't have a Mac any more, but it definitely involved an uninstall of Node and a reinstall of a version that had proper permissions.

**Comment by alisonatwork** [comment]
Ahhh, comment twins! Really great work on the new build, @OmgImAlexis . Works flawlessly out of the box on Windows.

**Comment by OmgImAlexis** [comment]
@alisonatwork oh thank god! I still need to get something like vagrant setup so I can do more testing with different OSs, mainly different Windows versions.

**Comment by Rycochet** [comment]
It's purely on work colleagues machines for projects I create at work - Node installed via the standard installer from their own site, and yes - on El Capitan - this isn't a support tracker for it, but it's it's a well known problem then might be worth linking to known fixes etc (bear in mind that "it works" is the important thing at work, and it's only really neededf or the standard uglify/libsass/postcss bits).

Speaking of which you've got "grunt-sass" and "grunt-contrib-sass" in the package.json, you only ened one (I'd suggest sticking to "grunt-sass" as it uses libsass which is platform agnostic, grunt-contrib-sass needs Ruby and Sass installed which means extra steps etc - looks like you're using the right one, but it's as obvious as missing {} in an if/else) - oh, and options in this can remove the need for cssmin ;-)

I'd also suggest running through an postcss + autoprefixer to support older browsers better (though not sure that it's needed for the main code - not checked, but everything seems simple enough) :-)

**Comment by OmgImAlexis** [comment]
@Rycochet yep node has the exact same issue on linux with apt-get, the "official" version of it is super broken. I suggest nvm for all OSs as it just works and also allowed things like installing multiple versions which is great when working with grunt locally so you can test if it'll break before allowing grunt to run on something like travis or circle-ci.

Yep, completely forgot to remove the other version of that. @alisonatwork said that SASS could only be compiled with the Ruby version and that's why we ended up with 2 of them. :stuck_out_tongue_winking_eye: Currently the cssmin package is for all of the code we're using now. Once I get everything into SASS I plan on removing that. :+1: 

I've thought about postcss and such but since all of the major browsers(Chrome, FireFox and Edge) are dropping support for vendor prefixes within the next year I figure there isn't much point in adding it especially when Chrome and Firefox have already remove a majority of the prefixes as of one of their last releases.

**Comment by fernandog** [comment]
https://github.com/SickRage/sickrage-issues/issues/117

**Comment by labrys** [comment]
#178

**Comment by fernandog** [comment]
@OmgImAlexis can you please make the "Subtitle" column to auto-size ? I have only one flag and is too large.

![image](https://cloud.githubusercontent.com/assets/2620870/11687534/5e61c5e0-9e6e-11e5-940e-e862d993b995.png)

@duramato

**Comment by OmgImAlexis** [comment]
@fernandog that's not a Javascript issue it's a CSS one.

````
th.col-subtitles,
td.col-subtitles {
    width: 150px;
    text-align: center;
}
````

Just remove the width in the different CSS files.

**Comment by fernandog** [comment]
@OmgImAlexis I set to width: auto

![image](https://cloud.githubusercontent.com/assets/2620870/11723796/4f549052-9f57-11e5-967a-3aae63d58daa.png)

is that ok?

**Comment by duramato** [comment]
It autoresizes now?

**Comment by fernandog** [comment]
without stopping SR, edit style.css and change to. save. full refresh
```css
th.col-subtitles,
td.col-subtitles {
    width: auto;
    text-align: center;
```

**Comment by duramato** [comment]
@fernandog 
![image](https://cloud.githubusercontent.com/assets/10121067/11725792/63ec17b2-9f73-11e5-88fc-151570f7261a.png)

**Comment by OmgImAlexis** [comment]
@fernandog just remove the width, it'll default to auto.

@duramato that's fine.

**Comment by fernandog** [comment]
@OmgImAlexis 

I'm getting this issues:
```
Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING - /js/vender.min.js?24022
Uncaught ReferenceError: topImageHtml is not defined - /js/lib/jquery.scrolltopcontrol-1.1.js?24022
```

**Comment by OmgImAlexis** [comment]
@fernandog sounds like you've got cache issues again or someone committed a broken vender file.

**Comment by neoatomic** [comment]
@OmgImAlexis For about a week the Kiwi IRC window under the IRC tab doesnt want to load anymore.
I'm using Firefox, and about the same time updated the Firefox version. I tested on Edge & Chrome and both work fine.
So i opened the console on the IRC page and gave me the bellow errors. : 

```  
setting default to undefined rootDirs.js:125:9
Gebruik van getPreventDefault() wordt niet meer ondersteund. Gebruik in plaats daarvan defaultPrevented. jquery-min.js:3:6333
SecurityError: The operation is insecure.
```

Translation : 
`wordt niet meer ondersteund. Gebruik in plaats daarvan` = `isn't supported anymore. Use instead`
`Gebruik van` = `Use of` 

Is there a way to get it to work again.?
Probably due to the fact the page is loaded as an in-frame page.? (also using https)

**Comment by duramato** [comment]
@neoatomic it doesnt work for me too on chrome

**Comment by OmgImAlexis** [comment]
@neoatomic I'll look into it.

**Comment by OmgImAlexis** [comment]
Looks fine to me. Guessing you're using it on a https connection?

````
setting default to undefined rootDirs.js:125:9
Gebruik van getPreventDefault() wordt niet meer ondersteund. Gebruik in plaats daarvan defaultPrevented. jquery-min.js:3:6333 
SecurityError: The operation is insecure.
````
1. That's normal
2. That's from jQuery being stupid.
3. Sounds like that's from a http iframe(IRC) loading on a https page.

**Comment by duramato** [comment]
```
kiwiirc.com/client/assets/kiwi.min.js?b=4:2 Uncaught (in promise) DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.(…)
https://owa.clients.kiwiirc.com/piwik.js Failed to load resource: net::ERR_INSECURE_RESPONSE```

**Comment by OmgImAlexis** [comment]
Well that sounds like an issue with kiwiirc and not SickRage then.

**Comment by miigotu** [comment]
I think we can work around it by connecting to the irc url in python, then using .get in IRC.mako. This could also be tweaked to maintain the IRC connection when you leave the IRC page unless you click a disconnect button on IRC.mako, and until it is loaded it could also show a loading spinner on the div =P

**Comment by fernandog** [comment]
@SickRage/moderators can someone confirm that in IE if you click the search hour glass in a list where it says searching it will say searching forever ?

**Comment by fernandog** [comment]
just to remind you about the jquery-ui-1.10.4.custom.min.css removal

**Comment by miigotu** [comment]
and what does that have to do with anything?

**Comment by fernandog** [comment]
We talked in IRC. that file should be removed

**Comment by fernandog** [comment]
@OmgImAlexis acording to @medariox:

every dialog with path selection:
https://snapr.pw/i/18fc0c9f98.png

**Comment by duramato** [comment]
Providers page also has a wierd Font now , bold-like
![image](https://cloud.githubusercontent.com/assets/10121067/12241163/6e789046-b889-11e5-89f3-597ebebd7c55.png)

**Comment by labrys** [comment]
@OmgImAlexis On metadata page:  Only results for KODI12+ are bold

**Comment by OmgImAlexis** [comment]
Everything to do with things being bold and/or not showing is why I wanted to use bower months ago. We have load of old broken CSS from when we were sickragetv.

@MGaetan89 any chance you can have a look at the CSS?

I'll have a look and see why it's causing the browse dialog to only show white. The hold issue can wait till @MGaetan89 can have a look as it doesn't actually break any functionality.

**Comment by labrys** [comment]
@OmgImAlexis Checkboxes for required/optional in apibuilder are broke too.

**Comment by OmgImAlexis** [comment]
Again.. this is why I told @MGaetan89 to use the vender file, ugh.

**Comment by OmgImAlexis** [comment]
@miigotu or @labrys can you look into this. The fonts should be sent using the [correct MIME type](https://stackoverflow.com/questions/2871655/proper-mime-type-for-fonts).

![screen shot 2016-01-12 at 12 25 26 pm](https://cloud.githubusercontent.com/assets/6525926/12252491/b7e7ed6e-b927-11e5-818c-597fdd126af9.png)

**Comment by OmgImAlexis** [comment]
Ref: https://github.com/SickRage/SickRage/pull/729

**Comment by miigotu** [comment]
Something strange about your cache? glyphicons are totally missing.

**Comment by miigotu** [comment]
SickRage/SickRage#730

**Comment by OmgImAlexis** [comment]
@miigotu can you add the fonts one to `/css/fonts` aswell or does that cover both?

**Comment by labrys** [comment]
@OmgImAlexis #471 a lot of pages don't refresh after submitting

**Comment by miigotu** [comment]
@OmgImAlexis bootstrap has fonts hard coded to ../fonts, thats why this handler needed added. css/fonts is handles by the regular css static handler.

**Comment by OmgImAlexis** [comment]
@miigotu ah okay, I figured all paths needed the specific handler. Does tornado not change the content type depending on the file extension or file header?

I'll look into adding bootstrap with the sass stuff we've got so we can change the path for the fonts for the future anyways.

**Comment by miigotu** [comment]
tornado does in fact guess the mime correctly. The problem was that it was redirecting the request to the home page with status 200 (because it was not found, same as going to `ip:port/blahblah`, so ofc that page was text/html.

I want to look into adding back a 404 page instead of redirecting home.

**Comment by fernandog** [comment]
@OmgImAlexis 

why JS code in mako?
using view-source in chrome - displayShow

```html
    <tbody class="tablesorter-no-sort">
        <tr style="height: 60px;">
            <th class="row-seasonheader displayShowTable" colspan="13" style="vertical-align: bottom; width: auto;">
                <h3 style="display: inline;"><a name="season-1"></a>Season 1</h3>
                    <button id="showseason-1" type="button" class="btn btn-xs pull-right" data-toggle="collapse" data-target="#collapseSeason-1">Show Episodes</button>
                    <script type="text/javascript">
                        $(function() {
                            $('#collapseSeason-1').on('hide.bs.collapse', function () {
                                $('#showseason-1').text('Show Episodes');
                            })
                            $('#collapseSeason-1').on('show.bs.collapse', function () {
                                $('#showseason-1').text('Hide Episodes');
                            })
                        });
                    </script>
            </th>
        </tr>
    </tbody>
```

**Comment by labrys** [comment]
@fernandog The js code is not in the mako.. the mako gets turned into the html, of which, the js is a part.  Doing a view source in chrome will thus show both.

**Comment by fernandog** [comment]
Ok. I got the `Uncaught ReferenceError: $ is not defined`. Just wondering. 
but I think this issue is related to the scene number change

**Comment by miigotu** [comment]
Stop trying to hack in ways to make shows work without season/ep.

**Comment by fernandog** [comment]
what are you talking about? wrong issue reply?

**Comment by OmgImAlexis** [comment]
@fernandog that's probably code I missed moving to the `core.js` before I did that there was js all through the mako files.

What file is that in?

**Comment by fernandog** [comment]
@OmgImAlexis displayShow.mako. thanks

**Comment by OmgImAlexis** [comment]
@miigotu when would `sickbeard.DISPLAY_ALL_SEASONS` be false? I'm not to sure that the js even gets used since it only gets added when that var is set to `False`.

**Comment by fernandog** [comment]
@OmgImAlexis it's a setting in SR interface tab

**Comment by OmgImAlexis** [comment]
Ah okay, I'll have to enable it to see what it's adding. Should be easy to fix. I'll finish watching my show and then fix it.

**Comment by fernandog** [comment]
@OmgImAlexis are you moving that JS ? thanks!

**Comment by OmgImAlexis** [comment]
Yeah it's been too hot to use my laptop, 40C/104F+ every day and night.

**Comment by fernandog** [comment]
@OmgImAlexis what do you think adding the #{tab-name} to the URL when clicking URL?

when clicking tab today, the url in address bar don't get updated with the tab name.

https://localshot:8081/config/providers/#provider-options

**Comment by OmgImAlexis** [comment]
There's no need to add the hash to the URL?
