### ISSUE TITLE
Network location based post-processing not working properly? (Windows/UNC)

### ISSUE THREAD

**Issue by xhorntail** [SickRage/old-sickrage-issues#1498]
Debugging was enabled during the log clips posted below.
**Branch/Commit:** master/10a0c3012e600ed61cdff6a6108b2bb55062907b
**OS:** Windows 10
**What you did:** Tried to manual post-process with network location. Of note, the service is being ran as a local user with access to the share. This worked fine prior to an update ~20-30 commits back.
**What happened:** Received error `Unable to figure out what folder to process. If your downloader and SickRage aren't on the same PC make sure you fill out your TV download dir in the config.` This happens regardless of Move/Copy.
**What you expected:** Usual post processing.
**Logs:**

**sickrage.log:**
```
2017-05-24 16:06:06 INFO     Thread-27 :: Beginning manual post processing task: \\TS5400DB22\Share\Torrents - Downloaded\SickRage
2017-05-24 16:06:06 DEBUG    Thread-27 :: Unable to figure out what folder to process. If your downloader and SickRage aren't on the same PC make sure you fill out your TV download dir in the config.
2017-05-24 16:06:06 INFO     Thread-27 :: Manual post processing task for \\TS5400DB22\Share\Torrents - Downloaded\SickRage completed
```

**General Configuration -> Show root directories:**
![screenshot_3](https://cloud.githubusercontent.com/assets/20708358/26429249/2212edde-40a3-11e7-82b6-6c3a1019362f.png)

**Manual post processing settings:**
![screenshot_2](https://cloud.githubusercontent.com/assets/20708358/26429190/c8c3ca8c-40a2-11e7-8924-847ffae95711.png)

**Manual post processing results:**
![screenshot_3](https://cloud.githubusercontent.com/assets/20708358/26429224/f18a634a-40a2-11e7-8083-6774010ff235.png)

**Comment by OmgImAlexis** [comment]
Please reopen this on this [correct repo](https://github.com/SickRage/SickRage/issues/new).
